apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qasuites.qa.company.com
  labels:
    app.kubernetes.io/name: qa-operator
    app.kubernetes.io/component: crd
spec:
  group: qa.company.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tests:
                type: array
                items:
                  type: string
                description: "List of QATest names to include in this suite"
              parallel:
                type: boolean
                default: false
                description: "Run tests in parallel"
              failFast:
                type: boolean
                default: false
                description: "Stop suite execution on first test failure"
              timeout:
                type: string
                default: "10m"
                description: "Suite execution timeout"
              schedule:
                type: string
                description: "Cron schedule for automated execution"
              environment:
                type: object
                additionalProperties:
                  type: string
                description: "Environment variables for test execution"
              preconditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["http", "dns", "tcp"]
                    endpoint:
                      type: string
                    timeout:
                      type: string
                      default: "30s"
                description: "Preconditions to check before running suite"
            required:
            - tests
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Succeeded", "Failed", "Partial"]
              lastRun:
                type: string
                format: date-time
              nextRun:
                type: string
                format: date-time
              runCount:
                type: integer
              successCount:
                type: integer
              failureCount:
                type: integer
              testResults:
                type: array
                items:
                  type: object
                  properties:
                    testName:
                      type: string
                    status:
                      type: string
                      enum: ["Pending", "Running", "Succeeded", "Failed"]
                    startTime:
                      type: string
                      format: date-time
                    endTime:
                      type: string
                      format: date-time
                    duration:
                      type: string
                    error:
                      type: string
  scope: Namespaced
  names:
    plural: qasuites
    singular: qasuite
    kind: QASuite
    shortNames:
    - qs