apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qaschedules.qa.company.com
  labels:
    app.kubernetes.io/name: qa-operator
    app.kubernetes.io/component: crd
spec:
  group: qa.company.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              schedule:
                type: string
                description: "Cron schedule for execution (e.g., '*/30 * * * *')"
              target:
                type: object
                properties:
                  kind:
                    type: string
                    enum: ["QATest", "QASuite"]
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - kind
                - name
              timezone:
                type: string
                default: "UTC"
                description: "Timezone for schedule execution"
              suspend:
                type: boolean
                default: false
                description: "Suspend schedule execution"
              startingDeadlineSeconds:
                type: integer
                minimum: 0
                maximum: 3600
                default: 60
                description: "Deadline for starting scheduled job"
              concurrencyPolicy:
                type: string
                enum: ["Allow", "Forbid", "Replace"]
                default: "Forbid"
                description: "How to handle concurrent executions"
              successfulJobsHistoryLimit:
                type: integer
                minimum: 0
                maximum: 10
                default: 3
              failedJobsHistoryLimit:
                type: integer
                minimum: 0
                maximum: 10
                default: 1
              jobTemplate:
                type: object
                properties:
                  spec:
                    type: object
                    properties:
                      backoffLimit:
                        type: integer
                        minimum: 0
                        maximum: 6
                        default: 2
                      ttlSecondsAfterFinished:
                        type: integer
                        minimum: 0
                        default: 300
            required:
            - schedule
            - target
          status:
            type: object
            properties:
              lastScheduleTime:
                type: string
                format: date-time
              lastSuccessfulTime:
                type: string
                format: date-time
              active:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    startTime:
                      type: string
                      format: date-time
  scope: Namespaced
  names:
    plural: qaschedules
    singular: qaschedule
    kind: QASchedule
    shortNames:
    - qsch