apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qatests.qa.company.com
  labels:
    app.kubernetes.io/name: qa-operator
    app.kubernetes.io/component: crd
spec:
  group: qa.company.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              endpoint:
                type: string
                description: "API endpoint to test"
              method:
                type: string
                enum: ["GET", "POST", "PUT", "DELETE", "PATCH"]
                default: "GET"
              headers:
                type: object
                additionalProperties:
                  type: string
                description: "HTTP headers to include"
              body:
                type: string
                description: "Request body for POST/PUT/PATCH"
              expectedStatus:
                type: integer
                minimum: 100
                maximum: 599
                default: 200
              expectedResponse:
                type: string
                description: "Expected response pattern (regex)"
              timeout:
                type: string
                default: "30s"
                description: "Request timeout"
              retries:
                type: integer
                minimum: 0
                maximum: 10
                default: 3
              interval:
                type: string
                default: "60s"
                description: "Test execution interval"
              notifications:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["slack", "email", "webhook"]
                    url:
                      type: string
                    channel:
                      type: string
                    recipients:
                      type: array
                      items:
                        type: string
            required:
            - endpoint
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Succeeded", "Failed"]
              lastRun:
                type: string
                format: date-time
              nextRun:
                type: string
                format: date-time
              runCount:
                type: integer
              successCount:
                type: integer
              failureCount:
                type: integer
              lastResult:
                type: object
                properties:
                  status:
                    type: integer
                  responseTime:
                    type: string
                  error:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
  scope: Namespaced
  names:
    plural: qatests
    singular: qatest
    kind: QATest
    shortNames:
    - qt