apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qa-dashboard.fullname" . }}
  labels:
    {{- include "qa-dashboard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qa-dashboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qa-dashboard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qa-dashboard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: qa-dashboard
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            # Secrets from Secret resource
            - name: DASHBOARD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "qa-dashboard.fullname" . }}-secrets
                  key: dashboardUsername
            - name: DASHBOARD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "qa-dashboard.fullname" . }}-secrets
                  key: dashboardPassword
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "qa-dashboard.fullname" . }}-secrets
                  key: slackWebhookUrl
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "qa-dashboard.fullname" . }}-secrets
                  key: discordWebhookUrl
            - name: TEAMS_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "qa-dashboard.fullname" . }}-secrets
                  key: teamsWebhookUrl
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "qa-dashboard.fullname" . }}-secrets
                  key: smtpUsername
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "qa-dashboard.fullname" . }}-secrets
                  key: smtpPassword
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
            successThreshold: {{ .Values.healthCheck.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /app/logs
              subPath: logs
            - name: data
              mountPath: /app/backup
              subPath: backup
            - name: config
              mountPath: /app/kilo_qa_checklist.json
              subPath: kilo_qa_checklist.json
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "qa-dashboard.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "qa-dashboard.fullname" . }}-config
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}