apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: qa-dashboard
    app.kubernetes.io/component: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: qa-platform
  source:
    repoURL: https://github.com/your-org/qa-platform
    path: helm-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment | default "dev" }}.yaml
      parameters:
        - name: image.tag
          value: $ARGOCD_APP_REVISION
  destination:
    server: https://kubernetes.default.svc
    namespace: qa-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10

---
# ApplicationSet for multi-environment deployment
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-platform-multienv
  namespace: argocd
  labels:
    app.kubernetes.io/name: qa-dashboard
    app.kubernetes.io/component: gitops
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: qa-dev
            cluster: https://kubernetes.default.svc
          - env: staging
            namespace: qa-staging
            cluster: https://kubernetes.default.svc
          - env: prod
            namespace: qa-prod
            cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'qa-platform-{{env}}'
      labels:
        app.kubernetes.io/name: qa-dashboard
        environment: '{{env}}'
    spec:
      project: qa-platform
      source:
        repoURL: https://github.com/your-org/qa-platform
        path: helm-chart
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
            - values-{{env}}.yaml
          parameters:
            - name: environment
              value: '{{env}}'
            - name: image.tag
              value: $ARGOCD_APP_REVISION
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      revisionHistoryLimit: 5